Howto page update
donategifts/donategifts-frontend pull request #30
Opened 2021-09-27 03:31 UTC by stacysealky

howto page header added

I will work on the rest of the page this week

2021-09-29 06:59 UTC, stacysealky commented
@Enubia can you review and merge? I'm done with this page for now

2021-09-29 13:54 UTC, Enubia requested changes

2021-09-29 13:54 UTC, Enubia commented on src/components/layout/BaseLayout.tsx
> +        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
please remove that, we don't need jquery anymore

2021-09-29 13:54 UTC, Enubia commented on src/pages/howto.tsx
> +      </section>
please use i18n for the translation stuff

2021-09-29 13:54 UTC, Enubia commented on src/styles/globals.scss
> +.cool-font {
this can all be set up in the tailwind.config.js file

2021-09-29 20:49 UTC, stacysealky commented on src/components/layout/BaseLayout.tsx
> +        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
ok

2021-09-29 21:22 UTC, stacysealky commented on src/pages/howto.tsx
> +      </section>
I'm not sure how to do that @Enubia

2021-09-29 21:22 UTC, stacysealky commented on src/styles/globals.scss
> +.cool-font {
ok fixed it

2021-09-29 21:48 UTC, Enubia commented on src/pages/howto.tsx
> +      </section>
You can take a look at how it's done in the mission page, if you're still not sure you can ask tokkiko about it since he did the initial implementation

2021-09-30 00:36 UTC, stacysealky commented on src/pages/howto.tsx
> +      </section>
@Enubia I added the i18next but I'm not utilizing the actual strings for translation on this page because our target is US-en and I feel like this can be added at a later stage instead of doing everything right now.

2021-10-01 03:35 UTC, merged