#63 - Rebuild UI for Contact Form.
donategifts/donategifts-frontend pull request #91
Opened 2022-09-26 03:40 UTC by deep-a

Task completed, please review and suggest changes. Thanks.

2022-09-26 07:47 UTC, Enubia requested changes
looks good overall

just two things
- make use of the translations
- merge the master after #88 was merged as this one includes some stuff that you probably need

2022-09-26 07:47 UTC, Enubia commented on src/pages/contact.jsx
> +                href="/faq">FAQ</a> page.</p>
use the Link component from next here

2022-09-26 23:56 UTC, deep-a commented on src/pages/contact.jsx
> +                href="/faq">FAQ</a> page.</p>
Can you please explain what you mean by using translations more? I switched to using the Link component and merged #88.

2022-09-27 11:36 UTC, Enubia commented on src/pages/contact.jsx
> +                href="/faq">FAQ</a> page.</p>
there are translation files located under ```/public/locales/en/```
bunch of json files, one for each page we have

please use them, example can be taken from the ```howTo.json``` and the howto.jsx

2022-09-28 02:19 UTC, deep-a commented on src/pages/contact.jsx
> +                href="/faq">FAQ</a> page.</p>
Thanks for the info, please review the changes.

2022-09-28 06:53 UTC, Enubia approved these changes

2022-09-28 06:55 UTC, merged